"""added message field

Revision ID: 931460632369
Revises: 21c6d0d7e97f
Create Date: 2023-01-08 20:11:47.451025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931460632369'
down_revision = '21c6d0d7e97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_1', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_3', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('photo_3')
        batch_op.drop_column('photo_2')
        batch_op.drop_column('photo_1')

    # ### end Alembic commands ###
